version: "3.8"

services:
  overwatch-api:
    # image: alfg/overwatch-api:latest
    build: ./
    ports:
      - "3000:3000"
    environment:
      - CACHE_TTL=30
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    
  redis:
    image: redis
    ports:
      - "6379:6379"